# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [1]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: 
# (1) C/Fortran computational efficiency, (2) Python language easy syntax 

# Let's define a one-dimensional array 
import numpy as np

my_list= [50,60,80,100,200,300]




In [2]:
# Let's create a numpy array from the list "my_list"
My_numpy_array = np.array(my_list)
My_numpy_array

array([ 50,  60,  80, 100, 200, 300])

In [5]:
type(My_numpy_array) # shows data type

numpy.ndarray

In [6]:
# Multi-dimensional (Matrix definition) 
my_matrix =np.array([[3,7, 9 ,3],
[4, 3, 2, 2]])

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [11]:
my_matrix = np.array([[3, 7, 9, 3], 
                      [4, 3, 2, 2]])
my_matrix

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS 

In [10]:
# "rand()" uniform distribution between 0 and 1
x= np.random.rand(20)
x

array([0.47066152, 0.42213125, 0.84113993, 0.35620085, 0.76933376,
       0.47313513, 0.29661742, 0.78658625, 0.87206997, 0.02177075,
       0.21876847, 0.2354154 , 0.93472196, 0.00926091, 0.61607269,
       0.88686293, 0.53397066, 0.08524717, 0.05498765, 0.74264242])

In [12]:
# you can create a matrix of random number as well
x= np.random.rand(3,3)  # create 3x3 matrix
x

array([[0.57037901, 0.80612448, 0.24780685],
       [0.23468509, 0.22973102, 0.63052283],
       [0.2766559 , 0.08759979, 0.81688988]])

In [16]:
# "randint" is used to generate random integers between upper and lower bounds
x= np.random.randint(1,50)  #generate a random integer between 1-50
x

49

In [17]:
# "randint" can be used to generate a certain number of random itegers as follows
x= np.random.randint(1,100,15)  # will generate 15 random integer no. between 1-100
x

array([88, 16, 39, 78, 50, 64, 32, 40, 82, 65, 44, 15, 41,  8,  5])

In [25]:
# np.arange creates an evenly spaced values within a given interval
x= np.arange(1,50,2)
x


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [32]:
# np.eye will create a diagonal of ones and zeros everywhere else
x= np.eye(7)
x


array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [30]:
# np.ones will Matrix of ones like bunch of ones 
x= np.ones((7,7))
x


array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [34]:
#  np.zeros will Array of zeros
x= np.zeros((7,7))
x

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [37]:
x= int(input("Please enter a positive integer value"))
x= np.random.randint(1,x,10)
x

Please enter a positive integer value5


array([3, 4, 4, 4, 2, 1, 2, 2, 3, 4])

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [38]:
# np.arange() returns an evenly spaced values within a given interval
x= np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
y= np.arange(1,10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
# Add 2 numpy arrays together
sum = x+y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
squared = x**2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [43]:
sqrt = np.sqrt(squared)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [44]:
z= np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [50]:
X = np.array([5,7,20])
Y = np.array([9,15,4])
Distance = np.round(np.sqrt(X**2 + Y**2),2)
Distance

array([10.3 , 16.55, 20.4 ])

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING 

In [52]:
my_numpy_arrray = np.array([3,5,6,2,8,10,20,50])
my_numpy_arrray

array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [54]:
# Access specific index from the numpy array , array count start from 0start, -1 (last element)
my_numpy_arrray[5]

10

In [57]:
# Starting from the first index 0 up until and NOT including the last element
my_numpy_arrray[0:3]

array([3, 5, 6])

In [59]:
# Broadcasting, altering several values in a numpy array at once
my_numpy_arrray[0:4]=7
my_numpy_arrray

array([ 7,  7,  7,  7,  8, 10, 20, 50])

In [62]:
matrix = np.random.randint(1,10,(4,4))
matrix

array([[7, 4, 4, 5],
       [1, 8, 5, 5],
       [4, 4, 1, 4],
       [7, 1, 9, 3]])

# Let's define a two dimensional numpy array


In [63]:
# Get a row from a mtrix
matrix[0]

array([7, 4, 4, 5])

In [67]:
# Get one element
matrix[0][0]

7

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [68]:
X = np.array([[2, 30, 20,-2, -4],
              [3, 4,  40, -3,-2],
              [-3, 4, -6, 90, 10],
              [25, 45, 34,22, 12],
              [13, 24, 22, 32, 37]])
X[4] =0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [69]:
matrix = np.random.randint(1,10,(5,5))
matrix

array([[5, 2, 2, 1, 1],
       [8, 2, 8, 1, 8],
       [3, 6, 7, 8, 5],
       [3, 9, 8, 9, 9],
       [7, 3, 9, 5, 6]])

In [72]:
new_matrix = matrix[matrix == 8]
new_matrix

array([8, 8, 8, 8, 8])

In [74]:
# Obtain odd elements only
new_matrix = matrix[matrix % 2 ==1]   
new_matrix

array([5, 1, 1, 1, 3, 7, 5, 3, 9, 9, 9, 7, 3, 9, 5])

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [84]:
x= np.array([[2, 30, 20 ,-2, -4],
             [3, 4,  40, -3, -2],
             [-3, 4, -6, 90, 10],
             [25, 45, 34, 22 ,12],
             [13, 24, 22, 32 ,37]])
x
x[x<0]=0
x[x%2==1]=-2
x

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [ ]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [85]:
import pandas as pd

In [88]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary
bank_client = pd.DataFrame({'Client_id': [11,22,33,44],
                            'Client_name':['Chanel', 'John','Shreya', 'Aditi'],
                            'Net_worth':['35000','40000','20000','50000']})
bank_client


Client_id Client_name Net_worth
0         11      Chanel     35000
1         22        John     40000
2         33      Shreya     20000
3         44       Aditi     50000

In [90]:
# Let's obtain the data type 
type(bank_client)

pandas.core.frame.DataFrame

In [92]:
# you can only view the first couple of rows using .head()
bank_client.head(2)

Client_id Client_name Net_worth
0         11      Chanel     35000
1         22        John     40000

In [93]:
# you can only view the last couple of rows using .tail()
bank_client.tail(1)

Client_id Client_name Net_worth
3         44       Aditi     50000

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

# TASK #7: PANDAS WITH CSV AND HTML DATA

In [96]:
# Pandas is used to read a csv file and store data in a DataFrame
House_pricde_canada = pd.read_html("https://www.livingin-canada.com/house-prices-canada.html")
House_pricde_canada[0]

City  \
0                                      Vancouver, BC   
1                                       Toronto, Ont   
2                                        Ottawa, Ont   
3                                       Calgary, Alb   
4                                      Montreal, Que   
5                                        Halifax, NS   
6                                       Regina, Sask   
7                                    Fredericton, NB   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                 Average House Price  \
0                                         $1,036,000   
1                                           $870,000   
2                                           $479,000   
3                                           $410,000   
4                                           $435,000   
5                                           $331,000   
6                                           $254,000   
7                                           $198,000   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                     12 Month Change  
0                                           + 2.63 %  
1                                            +10.2 %  
2                                           + 15.4 %  
3                                            – 1.5 %  
4                                            + 9.3 %  
5                                            + 3.6 %  
6                                            – 3.9 %  
7                                            – 4.3 %  
8  (adsbygoogle = window.adsbygoogle || []).push(...

In [97]:
House_pricde_canada[1]

Province  \
0                                    British Columbia   
1                                             Ontario   
2                                             Alberta   
3                                              Quebec   
4                                            Manitoba   
5                                        Saskatchewan   
6                                         Nova Scotia   
7                                Prince Edward Island   
8                             Newfoundland / Labrador   
9                                       New Brunswick   
10                                   Canadian Average   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                  Average House Price  \
0                                            $736,000   
1                                            $594,000   
2                                            $353,000   
3                                            $340,000   
4                                            $295,000   
5                                            $271,000   
6                                            $266,000   
7                                            $243,000   
8                                            $236,000   
9                                            $183,000   
10                                           $488,000   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                      12 Month Change  
0                                             + 7.6 %  
1                                             – 3.2 %  
2                                             – 7.5 %  
3                                             + 7.6 %  
4                                             – 1.4 %  
5                                             – 3.8 %  
6                                             + 3.5 %  
7                                             + 3.0 %  
8                                             – 1.6 %  
9                                             – 2.2 %  
10                                            – 1.3 %  
11  (adsbygoogle = window.adsbygoogle || []).push(...

# TASK #8: PANDAS OPERATIONS

In [120]:
# Let's define a dataframe as follows:
bank_client = pd.DataFrame({'Client_id': [11,22,33,44],
                            'Client_name':['Chanel', 'John','Shreya', 'Aditi'],
                            'Net_worth':['35000','40000','20000','50000']})
bank_client


Client_id Client_name Net_worth
0         11      Chanel     35000
1         22        John     40000
2         33      Shreya     20000
3         44       Aditi     50000

In [122]:
# Delete a column from a DataFrame
del bank_client['Net_worth']
bank_client

Client_id Client_name
0         11      Chanel
1         22        John
2         33      Shreya
3         44       Aditi

# TASK #9: PANDAS WITH FUNCTIONS

In [124]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [125]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 
def networth_update(balance):
    return balance*1.2

In [130]:
# You can apply a function to the DataFrame 

bank_client_df['Net worth [$]'].apply(networth_update)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

In [132]:
bank_client_df['Bank Client Name'].apply(len)

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [138]:
def networth_update(balance):
    return balance *3+200
results = bank_client_df['Net worth [$]'].apply(networth_update)
print(results)

0    10700
1    87200
2    30200
3     6200
Name: Net worth [$], dtype: int64


# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [139]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [140]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by ='Years with bank' )

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [142]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True


Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [143]:
# Set inplace = True to ensure that change has taken place in memory 
bank_client_df.sort_values(by ='Years with bank',  inplace = True)
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

#### Note that now the change (ordering) took place 


# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [ ]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

In [147]:
df1 = pd.DataFrame({ 'A':['A0','A1','A2','A3'],
                     'B':['B0','B1','B2','B3'],
                     'C':['C0','C1','C2','C3']},
                     index= [0,1,2,3])
df1

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3

In [148]:
df2 = pd.DataFrame({ 'A':['A4','A5','A6','A7'],
                     'B':['B4','B5','B6','B7'],
                     'C':['C4','C5','C6','C7']},
                     index= [4,5,6,7])
df2

A   B   C
4  A4  B4  C4
5  A5  B5  C5
6  A6  B6  C6
7  A7  B7  C7

In [150]:
df3 =  pd.DataFrame({ 'A':['A8','A9','A10','A11'],
                     'B':['B8','B9','B10','B11'],
                     'C':['C8','C9','C10','C11']},
                     index= [8,9,10,11])
df3

A    B    C
8    A8   B8   C8
9    A9   B9   C9
10  A10  B10  C10
11  A11  B11  C11

In [152]:
pd.concat([df1,df2,df3])

A    B    C
0    A0   B0   C0
1    A1   B1   C1
2    A2   B2   C2
3    A3   B3   C3
4    A4   B4   C4
5    A5   B5   C5
6    A6   B6   C6
7    A7   B7   C7
8    A8   B8   C8
9    A9   B9   C9
10  A10  B10  C10
11  A11  B11  C11

# TASK #12: PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

In [159]:
raw_Data= {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'], 
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}


Bank_df_1 = pd.DataFrame(raw_Data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1



Bank Client ID First Name  Last Name
0              6       Bill  Christian
1              7       Dina         Mo
2              8      Sarah      Steve
3              9    Heather        Bob
4             10      Holly   Michelle

In [160]:

# Let's define another dataframe for a separate list of clients (IDs = 6, 7, 8, 9, 10)
raw_data = {
        'Bank Client ID': ['6', '7', '8', '9', '10'],
        'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'], 
        'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2


# Let's assume we obtained additional information (Annual Salary) about our bank customers 
# Note that data obtained is for all clients with IDs 1 to 10 
raw_data = {
        'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary


# Let's concatenate both dataframes #1 and #2
# Note that we now have client IDs from 1 to 10
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all


# Let's merge all data on 'Bank Client ID'
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all


Bank Client ID First Name  Last Name  Annual Salary [$/year]
0              1      Nancy        Rob                   25000
1              2       Alex        Ali                   35000
2              3       Shep     George                   45000
3              4        Max      Mitch                   48000
4              5      Allen      Steve                   49000
5              6       Bill  Christian                   32000
6              7       Dina         Mo                   33000
7              8      Sarah      Steve                   34000
8              9    Heather        Bob                   23000
9             10      Holly   Michelle                   22000

In [161]:
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'], 
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

Bank Client ID First Name Last Name  Annual Salary [$/year]
0             11         Ry       Aly                    1000

In [162]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df

Bank Client ID First Name  Last Name  Annual Salary [$/year]
0              1      Nancy        Rob                   25000
1              2       Alex        Ali                   35000
2              3       Shep     George                   45000
3              4        Max      Mitch                   48000
4              5      Allen      Steve                   49000
5              6       Bill  Christian                   32000
6              7       Dina         Mo                   33000
7              8      Sarah      Steve                   34000
8              9    Heather        Bob                   23000
9             10      Holly   Michelle                   22000
0             11         Ry        Aly                    1000